### ISSUE TITLE
Footer link hover effect is too low contrast

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/concerto-docs#8]
# Bug Report 🐛
When a user hovers over a link in the footer, it changes into a color that's almost the same as the background, rendering it illegible.

## Expected Behavior
On hover, the link should change to a color that has high contrast with the background, so that it's legible. Or the link could have an underline effect appear and stay the same color. Ideally the footer would be visually and functionally consistent with the footer on https://docs.accordproject.org/ .

## Current Behavior
When a user hovers over a link in the footer, it changes into a color that's almost the same as the background, rendering it illegible.
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/40569793/231011377-ddea5652-d561-4075-ae75-f7691efe6488.png">

## Steps to Reproduce
1. Go to https://concerto.accordproject.org/
2. Scroll to the bottom of the page
3. Hover your cursor over one of the footer links

**Comment by jpatidar9826** [comment]
Please assign this issue to me and also can you direct me to the component which is rendering this section as i was not able to find that.
